---
project_identifier: faithlife-equipment
api_key: ebea0a7b4137298a7b2a0f50bb97f8d3
base_url: 'https://api.crowdin.com'
base_path: .
preserve_hierarchy: true
files:
  - source: '/packages/payment-methods/locales/en-US/resources.json'
    dest: '/payment-methods/resources.json'
    translation: '/packages/payment-methods/locales/%locale%/resources.%file_extension%'
    type: 'json'
